version: '3.8'

services:
  review-database:
    image: postgres:latest
    container_name: review-database
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_info:/var/lib/postgresql/info

  review-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "9003:9001"
    environment:
      REGISTRY_SERVER: service-registry
      DB_SERVER: review-database
      MANAGEMENT_METRICS_TAGS_APPLICATION: review-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: review-service
      OTEL_RESOURCE_ATTRIBUTES: compose_service=review-service
      OTEL_METRICS_EXPORTER: none
    depends_on:
      - review-database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_review
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test123
    ports:
      - "5051:80"

  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "14250:14250"
      - "4317:4317"
    depends_on:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./etc/dashboards:/etc/grafana/dashboards
      - ./etc/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    depends_on:
      - prometheus


volumes:
  postgres_info:
